import re

Future_Params = {
    'MA': {'rate_point': 2, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'AP': {'rate_point': 5, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'CJ': {'rate_point': 3, 'size': 5, 'slip': 1, 'slip_loss': 1, },
    'OI': {'rate_point': 2, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'SR': {'rate_point': 3, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'TA': {'rate_point': 3, 'size': 5, 'slip': 1, 'slip_loss': 1, },
    'SM': {'rate_point': 3, 'size': 5, 'slip': 1, 'slip_loss': 1, },
    'SF': {'rate_point': 3, 'size': 5, 'slip': 2, 'slip_loss': 1, },
    'CY': {'rate_point': 4, 'size': 5, 'slip': 5, 'slip_loss': 1, },
    'CF': {'rate_point': 4.3, 'size': 5, 'slip': 5, 'slip_loss': 1, },
    'RM': {'rate_point': 1.5, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'ZC': {'rate_point': 4, 'size': 100, 'slip': 0.2, 'slip_loss': 1, },
    'UR': {'rate_point': 5, 'size': 20, 'slip': 1, 'slip_loss': 1, },
    'WH': {'rate_point': 5, 'size': 20, 'slip': 1, 'slip_loss': 1, },
    'SA': {'rate_point': 3.5, 'size': 20, 'slip': 1, 'slip_loss': 1, },
    'FG': {'rate_point': 3, 'size': 20, 'slip': 1, 'slip_loss': 1, },
    'JR': {'rate_point': 3, 'size': 20, 'slip': 1, 'slip_loss': 1, },
    'LR': {'rate_point': 3, 'size': 20, 'slip': 1, 'slip_loss': 1, },
    'PM': {'rate_point': 5, 'size': 50, 'slip': 1, 'slip_loss': 1, },
    'RI': {'rate_point': 2.5, 'size': 20, 'slip': 1, 'slip_loss': 1, },
    'RS': {'rate_point': 2, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'J': {'rate': 6E-05, 'size': 100, 'slip': 0.2, 'slip_loss': 1, },
    'JM': {'rate': 6E-05, 'size': 60, 'slip': 0.2, 'slip_loss': 1, },
    'A': {'rate_point': 2, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'JD': {'rate': 0.00015, 'size': 5, 'slip': 1, 'slip_loss': 1, },
    'P': {'rate_point': 2.5, 'size': 10, 'slip': 2, 'slip_loss': 1, },
    'Y': {'rate_point': 2.5, 'size': 10, 'slip': 2, 'slip_loss': 1, },
    'CS': {'rate_point': 1.5, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'L': {'rate_point': 2, 'size': 5, 'slip': 5, 'slip_loss': 1, },
    'PP': {'rate': 6E-05, 'size': 5, 'slip': 1, 'slip_loss': 1, },
    'M': {'rate_point': 1.5, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'BB': {'rate': 0.0001, 'size': 500, 'slip': 0.05, 'slip_loss': 1, },
    'V': {'rate_point': 2, 'size': 5, 'slip': 5, 'slip_loss': 1, },
    'EG': {'rate_point': 4, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'C': {'rate_point': 1.2, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'FB': {'rate': 0.0001, 'size': 500, 'slip': 0.5, 'slip_loss': 1, },
    'PG': {'rate_point': 6, 'size': 20, 'slip': 1, 'slip_loss': 1, },
    'B': {'rate_point': 1, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'EB': {'rate_point': 6, 'size': 5, 'slip': 1, 'slip_loss': 1, },
    'I': {'rate': 0.0001, 'size': 100, 'slip': 0.5, 'slip_loss': 1, },
    'RR': {'rate_point': 4, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'CU': {'rate': 5E-05, 'size': 5, 'slip': 10, 'slip_loss': 1, },
    'ZN': {'rate_point': 3, 'size': 5, 'slip': 5, 'slip_loss': 1, },
    'AL': {'rate_point': 3, 'size': 5, 'slip': 5, 'slip_loss': 1, },
    'SN': {'rate_point': 3, 'size': 1, 'slip': 10, 'slip_loss': 1, },
    'PB': {'rate': 4E-05, 'size': 25, 'slip': 5, 'slip_loss': 1, },
    'AU': {'rate_point': 10, 'size': 1000, 'slip': 0.01, 'slip_loss': 1, },
    'WR': {'rate': 4E-05, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'SP': {'rate': 5E-05, 'size': 10, 'slip': 2, 'slip_loss': 1, },
    'FU': {'rate': 5E-05, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'RB': {'rate': 0.0001, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'HC': {'rate': 0.0001, 'size': 10, 'slip': 1, 'slip_loss': 1, },
    'BU': {'rate': 0.0001, 'size': 10, 'slip': 2, 'slip_loss': 1, },
    'SS': {'rate': 0.0001, 'size': 5, 'slip': 5, 'slip_loss': 1, },
    'NI': {'rate_point': 6, 'size': 1, 'slip': 10, 'slip_loss': 1, },
    'AG': {'rate': 5E-05, 'size': 15, 'slip': 1, 'slip_loss': 1, },
    'RU': {'rate': 4.5E-05, 'size': 10, 'slip': 5, 'slip_loss': 1, },
}


def get_symbol_flag(symbol):
    flag = re.sub('\\d', "", symbol)
    return flag
